version = '2'

[linters]
default = 'all'
disable = [
  'containedctx',
  'contextcheck',
  'cyclop',
  'depguard',
  'dupl',
  'embeddedstructfieldcheck',
  'err113',
  'errchkjson',
  'exhaustive',
  'exhaustruct',
  'forcetypeassert',
  'funlen',
  'gochecknoglobals',
  'gochecknoinits',
  'gocognit',
  'gocritic',
  'gocyclo',
  'godot',
  'godox',
  'gosec',
  'ireturn',
  'lll',
  'loggercheck',
  'maintidx',
  'mnd',
  'nestif',
  'nilnil',
  'nlreturn',
  'nonamedreturns',
  'paralleltest',
  'revive',
  'tagliatelle',
  'testpackage',
  'thelper',
  'unparam',
  'varnamelen',
  'wastedassign',
  'wrapcheck',
  'wsl'
]

[linters.settings]
[linters.settings.errcheck]
exclude-functions = [
  'fmt.Fprintf'
]

[linters.settings.goconst]
min-len = 3
min-occurrences = 3

[linters.settings.gocyclo]
min-complexity = 12

[linters.settings.godot]
exclude = [
  ' \+'
]

[linters.settings.misspell]
locale = 'US'

[linters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[issues]
max-same-issues = 0

[formatters]
enable = [
  'gofmt',
  'goimports'
]

[formatters.settings]
[formatters.settings.gci]
sections = [
  'prefix(github.com/DataDog/extendeddaemonset)'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
