kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: extendeddaemonset
subjects:
- kind: ServiceAccount
  namespace: default
  name: extendeddaemonset
roleRef:
  kind: ClusterRole
  name: extendeddaemonset
  apiGroup: rbac.authorization.k8s.io

