apiVersion: apps/v1
kind: Deployment
metadata:
  name: extendeddaemonset
spec:
  replicas: 1
  selector:
    matchLabels:
      name: extendeddaemonset
  template:
    metadata:
      labels:
        name: extendeddaemonset
    spec:
      serviceAccountName: extendeddaemonset
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
        - name: extendeddaemonset
          image: datadog/extendeddaemonset:latest
          imagePullPolicy: IfNotPresent
          command:
          - extendeddaemonset
          args:
            - --zap-level=2
          env:  
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "extendeddaemonset"
