apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: extendeddaemonset
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - services
  verbs:
  - '*'
- apiGroups:
  - datadoghq.com
  resources:
  - extendeddaemonsets
  - extendeddaemonsets/status
  - extendeddaemonsetreplicasets
  - extendeddaemonsetreplicasets/status
  verbs:
  - '*'
