apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: extendeddaemonset
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - extendeddaemonset-lock
  verbs:
  - update
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - watch
- apiGroups:
  - datadoghq.com
  resources:
  - 'extendeddaemonsets'
  - 'extendeddaemonsets/status'
  - 'extendeddaemonsetreplicasets'
  - 'extendeddaemonsetreplicasets/status'
  - 'extendednodes'
  - 'extendednodes/status'
  verbs:
  - '*'
