apiVersion: datadoghq.com/v1alpha1
kind: ExtendedDaemonSet
metadata:
  name: foo
spec:
  strategy:
    canary:
      replicas: 2
      duration: 30m
    rollingUpdate:
      maxParallelPodCreation: 10
      slowStartIntervalDuration: 2m
  template:
    spec: 
      containers:
      - name: daemon
        image: k8s.gcr.io/pause:3.0
