{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "extendeddaemonset.fullname" . }}
  labels:
{{ include "extendeddaemonset.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - services
  verbs:
  - '*'
- apiGroups:
  - datadoghq.com
  resources:
  - 'extendeddaemonsets'
  - 'extendeddaemonsets/status'
  - 'extendeddaemonsetreplicasets'
  - 'extendeddaemonsetreplicasets/status'
  verbs:
  - '*'
{{- end -}}
