apiVersion: datadoghq.com/v1alpha1
kind: ExtendedDaemonSet
metadata:
  name: foo
spec:
  strategy:
    canary:
      replicas: 1
      duration: 5m
      autoPause:
        maxRestarts: 5
        enabled: true
    rollingUpdate:
      maxParallelPodCreation: 1
      slowStartIntervalDuration: 1m
  template:
    spec:
      containers:
      - name: daemon
        image: k8s.gcr.io/pause:3.1
      tolerations:
      - operator: Exists
