apiVersion: datadoghq.com/v1alpha1
kind: ExtendedDaemonSet
metadata:
  name: foo
spec:
  strategy:
    canary:
      replicas: 1
      duration: 5m
      autoFail:
        enabled: true
        canaryTimeout: 10m
    rollingUpdate:
      maxParallelPodCreation: 1
      maxUnavailable: 2
      slowStartIntervalDuration: 1m
  template:
    spec: 
      containers:
      - name: daemon
        image: k8s.gcr.io/pause:3.0
      tolerations:
      - operator: Exists
