apiVersion: datadoghq.com/v1alpha1
kind: ExtendedDaemonSet
metadata:
  name: foo
spec:
  strategy:
    canary:
      replicas: 1
      duration: 5m
    rollingUpdate:
      maxParallelPodCreation: 1
      slowStartIntervalDuration: 1m
  template:
    spec: 
      containers:
      - name: daemons
        image: k8s.gcr.io/pause:3.1
      tolerations:
      - operator: Exists
