name: build-cgo

on:
  push:

jobs:
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: gcc install
        run: sudo apt install gcc-aarch64-linux-gnu
      - name: Get tag
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tag
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Get Latest Release
        id: latest_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            owner: ${{ github.repository_owner }}
            repo: extendeddaemonset
            excludes: prerelease, draft
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --skip-publish --config .goreleaser-for-linux.yaml
        env:
          GORELEASER_PREVIOUS_TAG: ${{steps.latest_version.outputs.release}}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: kubectl-eds-linux
          path: |
            dist/kubectl-eds_*.zip
            dist/checksums.txt
  build-darwin-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get tag
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tag
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Get Latest Release
        id: latest_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            owner: ${{ github.repository_owner }}
            repo: extendeddaemonset
            excludes: prerelease, draft
      - name: Build
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --skip-publish --config .goreleaser-for-darwin.yaml
        env:
          GORELEASER_PREVIOUS_TAG: ${{steps.latest_version.outputs.release}}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: kubectl-eds-darwin
          path: |
            dist/kubectl-eds_*.zip
            dist/checksums.txt
  build-windows-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get tag
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tag
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Get Latest Release
        id: latest_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            owner: ${{ github.repository_owner }}
            repo: extendeddaemonset
            excludes: prerelease, draft
      - name: Build
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --skip-publish --config .goreleaser-for-windows.yaml
        env:
          GORELEASER_PREVIOUS_TAG: ${{steps.latest_version.outputs.release}}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: kubectl-eds-windows
          path: |
            dist/kubectl-eds_*.zip
            dist/checksums.txt
  create-release:
    needs: [build-linux-binary, build-darwin-binary, build-windows-binary]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make directories
        run: |
          mkdir -p ./dist/linux
          mkdir -p ./dist/darwin
          mkdir -p ./dist/windows
      - name: Download linux binaries
        uses: actions/download-artifact@v3
        with:
          name: kubectl-eds-linux
          path: ./tmp-build/linux
      - name: Download darwin binaries
        uses: actions/download-artifact@v3
        with:
          name: kubectl-eds-darwin
          path: ./tmp-build/darwin
      - name: Download windows binaries
        uses: actions/download-artifact@v3
        with:
          name: kubectl-eds-windows
          path: ./tmp-build/windows
      - name: Get tag
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tag
      - name: Prepare ./dist folder
        run: |
          mkdir -p ./dist
          cat ./tmp-build/darwin/checksums.txt >> ./dist/checksums.txt
          cat ./tmp-build/linux/checksums.txt >> ./dist/checksums.txt
          cat ./tmp-build/windows/checksums.txt >> ./dist/checksums.txt
          mv ./tmp-build/darwin/*.zip ./dist
          mv ./tmp-build/linux/*.zip ./dist
          mv ./tmp-build/windows/*.zip ./dist
      - name: Generate Plugin manifest
        run: ./hack/release/generate-plugin-manifest.sh 0.9.0-test-cgo
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: kubectl-eds-final
          path: |
            ./dist/*.zip
            ./dist/checksums.txt
            ./dist/eds-plugin.yaml
            ./LICENSE
